---
title: "distribution"
author: "Jianqiu Zheng"
date: "8/25/2021"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(reshape2)
library(dplyr)
library(ggpubr)
library(scales)
library(MASS)
```


###spatial distance
```{r probobility}
##create the log normal distribution
y=rnorm(1000,-4,0.25) #define stdev as 0.25,1,2 
delta<-10^(y) ##diffusion distance
std<-sd(delta)



median(delta)
mean(delta)
#delta[delta<5e-5]<-0

test<-data.frame(y=y)
test$dist<-delta


p1<-ggplot(test, aes(x=dist))+geom_density(color="#7f3b08", size=1.2)+
  scale_x_log10(name = "Distance (m)",limits=c(10^-6, 10^-2),breaks = trans_breaks("log10", function(x) 10^x),
              labels = trans_format("log10", math_format(10^.x)))+ geom_vline(xintercept=10^-4, linetype="dashed")+
  scale_y_continuous(name="Density", limits=c(0,1), breaks=c(0,0.5,1))+
  coord_flip()
p2<-p1+theme_linedraw()+theme(panel.background = element_rect(fill = "transparent",colour = NA),
                                    plot.background = element_rect(fill = "transparent",colour = NA),
                                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  theme(text = element_text(size=16))
print(p2)



index<-seq(1,1000,1)
test<-data.frame(index=index)
test$dis<-delta
ptest<-melt(test, id.vars="index")

p1<-ggplot(ptest, aes(x=index, y=value, color=variable))+geom_point(aes(color=variable), shape=21, size=1.2, stroke=0.5) + scale_color_manual(values=c("#7f3b08","#542788"))+
  scale_y_log10(name="Distance (m)",limits=c(10^-6, 10^-2),breaks = trans_breaks("log10", function(x) 10^x),
              labels = trans_format("log10", math_format(10^.x)))




p2<-p1+theme_linedraw()+theme(panel.background = element_rect(fill = "transparent",colour = NA),
                                    plot.background = element_rect(fill = "transparent",colour = NA),
                                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  theme(text = element_text(size=16))
print(p2)


y1=rnorm(1000,-4,0.25) #define stdev as 0.25, 0.5, 1 
doc<-10^(y1) ##diffusion distance

index<-seq(1,1000,1)
test<-data.frame(index=index)
test$dis<-delta
test$con<-doc
ptest<-melt(test, id.vars="index")

p1<-ggplot(ptest, aes(x=index, y=value, color=variable))+geom_point(aes(color=variable), shape=21, size=0.8, stroke=0.2) + scale_color_manual(values=c("#7f3b08","#542788"))+
  scale_y_log10(name="Distance (m)/Csoil(M)",limits=c(10^-6, 10^-2),breaks = trans_breaks("log10", function(x) 10^x),
              labels = trans_format("log10", math_format(10^.x)))




p2<-p1+theme_linedraw()+theme(panel.background = element_rect(fill = "transparent",colour = NA),
                                    plot.background = element_rect(fill = "transparent",colour = NA),
                                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  theme(text = element_text(size=10),legend.position = "none")
print(p2)


#pdf("delta_distribution_soc.pdf", width=1.5, height=1.8)
p2
#dev.off()
```



```{r testing}
#===========create dataset====================
#clay po=0.58, org=0.013, bd=1.1, clay=0.58
#clay loam po=0.71, org=0.101, bd=0.7, clay=0.3
#loam sand po=0.48, org=0.014, bd=1.35, clay=0.09

rs<-seq(0.05,0.95,0.01)
po<-0.7
org<-0.101
mvol<-po*rs
bd<-0.7
soc<-org/12*bd*1e-3  #assum ss 1% as DOC  (mol/cm3) and 10% of these DOC are accessible
oxy<-(po-mvol)*0.2*0.04  #in mol/L
  
#soc<-1e-6 # in mol DOC /cm3 soil (=1000 uM)---0.023
#oxy<-1e-6 # in mol/cm3 (=1000 uM)
theta<-mvol/0.8#thaR=0,thaS=0.7
t1<-theta^(-1/0.33)-1#n=1.5, alpha=0.03, m=0.33
t2<-t1^(1/1.5)/0.03
data<-data.frame(rs=rs)
data$mvol<-mvol
data$po<-po
data$bd<-bd
data$mp<-t2
data$soc<-soc
data$oxy<-oxy
#silt loam po=0.58, org=0.022, bd=1.1, clay=0.17
#sandy loam po=0.86, org=0.126, bd=0.46, clay=0.04
#silt clay po=0.62, org=0.016, bd=1, clay=0.46
```


##Aerobic pathway only with varying diffusion distance
```{r distribution}
#====Mass transfer distance====
solveCSS<-function(mvol,po,bd,delta,soc,oxy,kmc,kmo,vmax){
  Ds0=1.4e-9 #(glucose 10^-11) #aqueous tracer diffusivity at 25 (m2/s)
  Dg0=2.1e-5#oxygen diffusivity in water
  fDg<-(po)^1.5*((po-mvol)/(po))^2.5 #gas phase relative diffusivity
  fDs<-(po)^1.5*((mvol)/(po))^2.5 #aqueous phase relative diffusivity
  H_o2<-1.3e-6  #mol/cm3/atm
  hs<-6/(mvol+bd*10)*Ds0*fDs/(delta^2) #DOM delivery (mass transfer rate in d-1)
  hg<-6/(mvol+bd*1)*Dg0*fDg*H_o2/(delta^2)  #DO delivery (mass transfer rate)
  ac<-kmc/soc #Km/Csoil
  bc<-vmax/(hs*soc)#Fuptake/Fdiff
  t1c<-(1-4*bc/(1+ac+bc)^2)^0.5
  F1c<-(1+ac+bc)/2/bc*(1-t1c) #uptake flux
  css<-F1c*kmc/(1-F1c) #steady state concentration
  cstar<-soc/(soc+kmc+vmax/hs)
  ag<-kmo/oxy
  bg<-vmax/(hg*oxy)
  t1g<-(1-4*bg/(1+ag+bg)^2)^0.5
  F1g<-(1+ag+bg)/2/bg*(1-t1g)
  oss<-F1g*kmo/(1-F1g)
  rate<-vmax*css/(css+kmc)*oss/(oss+kmo)*delta^3 #per colony
  return (rate)}



simrun<-function(data, delta){
t_result<-data.frame(nrow=1000)

for (i in 1:length(delta)){

  new<-solveCSS(data$mvol, data$po, data$bd, delta[i], doc[i], data$oxy, 1e-5, 1e-4,1.16e-6)#vmax=1 d-1
  #nvol<-new*delta[i]^3
  t_result = cbind(t_result, new)} ##per colony

 return (t_result)
    }
 
stat_sum<-simrun(data, delta)


features <- c(sprintf("pred%02d", seq(0,1000)))
colnames(stat_sum) <- features

#vol<-sum(delta^3)

colnames(stat_sum) [1]<- "rs"
stat_sum$rs<-data$rs      
pred_sum<-melt(stat_sum, id.vars="rs")
maxc<-max(pred_sum$value)
pred_sum$value<-pred_sum$value/maxc


flux_ave<-data.frame(rs=stat_sum[,1], means=rowMeans(stat_sum[,-1]))

#row_sum<-data.frame(rs=stat_sum[,1], sum=rowSums(stat_sum[,-1]))
#flux_sum<-row_sum/vol






plot1<-ggplot(pred_sum, aes(x = rs,y=value, color=variable)) + 
  scale_x_continuous(name = "Relative saturation",limits = c(0,1)) +
  scale_y_continuous(name = "Relative HR",limits = c(0,1))+
  geom_line(aes(group=variable), color="#b2abd2",linetype="solid", alpha=0.05,size=0.5)

plot2<-plot1+theme_linedraw()+theme(panel.background = element_rect(fill = "transparent",colour = NA),
                                    plot.background = element_rect(fill = "transparent",colour = NA),
                                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  theme(text = element_text(size=16))
print(plot2)

delta1<-median(delta)
delta2<-mean(delta)

doc1<-median(doc)

ava1<-solveCSS(data$mvol, data$po, data$bd, delta1, doc1, data$oxy, 1e-5, 1e-4,1.16e-6)#vmax=1 d-1



fave<-data.frame(rs=rs)
fave$mean<-flux_ave$means/maxc
pfave<-melt(fave, id.vars="rs")

fmac<-data.frame(rs=rs)
fmac$mean<-ava1/maxc
pfmac<-melt(fmac, id.vars="rs")

plot1<-ggplot(pred_sum, aes(x = rs,y=value, color=variable)) + 
  scale_x_continuous(name = "Relative saturation",limits = c(0,1)) +
  scale_y_continuous(name = "Normalized uptake")+
  geom_line(aes(group=variable), color="#b2abd2",linetype="solid", alpha=0.05,size=0.5)+
  geom_line(data=pfave, color="#7f3b08", size=1.4)+
  geom_line(data=pfmac, color="#717171", size=1.4)

plot2<-plot1+theme_linedraw()+theme(panel.background = element_rect(fill = "transparent",colour = NA),
                                    plot.background = element_rect(fill = "transparent",colour = NA),
                                     panel.grid = element_blank(),panel.grid.minor = element_blank())+
  theme(text = element_text(size=10))
print(plot2)


#pdf("loamsand_doc_2.pdf", width=2.4, height=1.8)
plot2
#dev.off()


```


```{r label}
test<-data.frame(rs=rs)
test$data1<-0.2
test$data2<-0.5
test$data3<-0.8
ptest<-reshape2::melt(test, id.vars=c("rs"))

plot1<-ggplot(ptest, aes(x = rs,y=value, color=variable)) + 
  scale_x_continuous(name = "Relative saturation",limits = c(0,1)) +
  scale_y_continuous(name = "Relative HR",limits = c(0,1))+
  geom_line(aes(color=variable),size=1.6)+
  scale_color_manual(values = c("#b2abd2","#060606", "#717171"))

plot2<-plot1+theme_linedraw()+theme(panel.background = element_rect(fill = "transparent",colour = NA),
                                    plot.background = element_rect(fill = "transparent",colour = NA),
                                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  theme(text = element_text(size=16))

pdf("labels.pdf", width=3.6, height=2.8)
plot2
dev.off()

```


####varying SOC concentration
```{r distribution}
#====Mass transfer distance====
solveCSS<-function(mvol,po,bd,delta,soc,oxy,kmc,kmo,vmax){
  Ds0=1.4e-9 #(glucose 10^-11) #aqueous tracer diffusivity at 25 (m2/s)
  Dg0=2.1e-5#oxygen diffusivity in water
  fDg<-(po)^1.5*((po-mvol)/(po))^2.5 #gas phase relative diffusivity
  fDs<-(po)^1.5*((mvol)/(po))^2.5 #aqueous phase relative diffusivity
  H_o2<-1.3e-6  #mol/cm3/atm
  hs<-6/(mvol+bd*10)*Ds0*fDs/(delta^2) #DOM delivery (mass transfer rate in d-1)
  hg<-6/(mvol+bd*1)*Dg0*fDg*H_o2/(delta^2)  #DO delivery (mass transfer rate)
  ac<-kmc/soc #Km/Csoil
  bc<-vmax/(hs*soc)#Fuptake/Fdiff
  t1c<-(1-4*bc/(1+ac+bc)^2)^0.5
  F1c<-(1+ac+bc)/2/bc*(1-t1c) #uptake flux
  css<-F1c*kmc/(1-F1c) #steady state concentration
  cstar<-soc/(soc+kmc+vmax/hs)
  ag<-kmo/oxy
  bg<-vmax/(hg*oxy)
  t1g<-(1-4*bg/(1+ag+bg)^2)^0.5
  F1g<-(1+ag+bg)/2/bg*(1-t1g)
  oss<-F1g*kmo/(1-F1g)
  rate<-vmax*css/(css+kmc)*oss/(oss+kmo)
  return (rate)}



simrun<-function(data, delta){
t_result<-data.frame(nrow=500)

for (i in 1:length(delta)){

  new<-solveCSS(data$mvol, data$po, data$bd, 1e-4, delta[i], data$oxy, 1e-5, 1e-5,1.16e-5)#vmax=1 d-1

  t_result = cbind(t_result, new/max(new))}

 return (t_result)
    }
 
stat_sum<-simrun(data, delta)


features <- c(sprintf("pred%02d", seq(0,500)))
colnames(stat_sum) <- features

colnames(stat_sum) [1]<- "rs"
stat_sum$rs<-data$rs      

flux_ave<-data.frame(rs=stat_sum[,1], means=rowMeans(stat_sum[,-1]))

pred_sum<-melt(stat_sum, id.vars="rs")




plot1<-ggplot(pred_sum, aes(x = rs,y=value, color=variable)) + 
  scale_x_continuous(name = "Relative saturation",limits = c(0,1)) +
  scale_y_continuous(name = "Relative HR",limits = c(0,1))+
  geom_line(aes(group=variable), color="#b2abd2",linetype="solid", alpha=0.1,size=1)

plot2<-plot1+theme_linedraw()+theme(panel.background = element_rect(fill = "transparent",colour = NA),
                                    plot.background = element_rect(fill = "transparent",colour = NA),
                                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  theme(text = element_text(size=16))
print(plot2)

delta1<-median(delta)
delta2<-mean(delta)

ava1<-solveCSS(data$mvol, data$po, data$bd, 1e-4,delta1, data$oxy, 1e-5, 1e-5,1.16e-5)#vmax=1 d-1
ava2<-solveCSS(data$mvol, data$po, data$bd, 1e-4,delta2,data$oxy, 1e-5, 1e-5,1.16e-5)#vmax=1 d-1

# Create a transparent theme object
transparent_theme <- theme(
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  axis.text.x = element_blank(), 
  axis.text.y = element_blank(),
  axis.ticks = element_blank(),
  panel.grid = element_blank(),
  axis.line = element_blank(),
  legend.position = "none",
  panel.background = element_rect(fill = "transparent",colour = NA),
  plot.background = element_rect(fill = "transparent",colour = NA))

emp<-data.frame(rs=rs)
emp$ave<-flux_ave$means/(max(flux_ave$means))
emp$mean<-ava1/max(ava1)
pave<-reshape2::melt(emp, id.vars=c("rs"))

##creat Grib
##mean flux in black, mean parameter in gray (median distance)
bp<-ggplot(pave, aes(x = rs,y = value, color=variable))+ geom_line(aes(color=variable),size=1.4)+
  scale_color_manual(values = c("#060606", "#717171"))+
  transparent_theme

bp_grob<-ggplotGrob(bp)#create the external graphcal elements (called a grop in Grid terminology)
ymin<--0.08
xmin<--0.03
plot7<-plot2+annotation_custom(grob=bp_grob, xmin =xmin, xmax=xmin+1.04, ymin=ymin, ymax=ymin+1.15)
print(plot7)



#pdf("siltloam_distance_25.pdf", width=3.6, height=2.8)
plot7
#dev.off()

```
